name: Build & Test
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: true
          matrix:
            dotnet-version: [ '5.0.x' ]

        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET Core SDK ${{matrix.dotnet-version}}
              uses: actions/setup-dotnet@v2
              with:
                dotnet-version: ${{ matrix.dotnet-version }}
            - name: Install Depedencies
              run: dotnet restore
            - name: Build
              run: dotnet build --configuration Release --no-restore
            - name: Test
              run: dotnet test --no-restore --verbosity normal
